= Activities

== Issue status

[width="100%",cols="9,1",options="header"]
|====
| Issue | Resolved?
| AWS Cloudforms Provisioning  | Y
| Data Center move | Y
| Fibre Optic hardware compatibility | N
| OpenStack Cloudforms Provisioning  | N
|====

== Lester Claudio's activity log
* Instance tagging is done.  We need to discuss how I came up with the use case.
* reated an example Group and Role taxonomy that we will need to show Yale NUS to see if it works for them.
* Sample groups created in support of YaleNUS Self-Service: 
** YaleNUS-Admin - Basic YaleNUS Administrator group. Will have superuser capabilities.
** YaleNUS-<Project> - User group to be associated with their current project.
** YaleNUS-<Project>-Admin - This is the Project Administrator ... Professor.
    Unfortunately we will have to have one of these for each project/course.  The group needs to be created in MS AD and the administrator will import it into Cloudforms.

* Added the EBS dialogs and buttons.
* Rake scripts to import/export dialogs, buttons, service_dialogs etc 

== George Goh's activity log
* Added BuildRequest method for OpenStack provisioning. This adds the ability to provision more than 1 VM in a request.
* Previously created tags/groups to represent projects in Yale-NUS. This was done on request of Yale-NUS due to their lack of control over the corporate(NUS) AD administration. However, integration with projects can be made more seamless if this can be modified in AD. We will need to discuss with Yale-NUS further on this.
* Set up the Development machine for OpenStack on http://172.18.17.226 while issues with the target production hardware are being resolved.
* Set up the Development CloudForms appliance on the dev OpenStack machine on https://172.18.17.126/. Accounts for AWS and the dev OpenStack machine, as well as Yale-NUS AD connections were set up on this instance.
* Previously added Cinder volume functionality. Will need to revisit this to achieve parity with Lester's work.

