= OpenStack Deployment

== Overview
Overview of YaleNUS OpenStack environment 

=== Pre-requisites
* List pre-requisites

* Server Racked, Stacked and Cabled
* Switch configuration completed

=== Versions
[width="100%"]
|====
| OS Version | RHEL 6.6 x86_64
| Red Hat OpenStack Version | RHOS Version x.x
|====

=== Architecture
* 1x Manamgement Node 
* 3x Nodes 

[width="100%"]
|====
| RAM | 128 GB
| OS Disk | 2x 300GB
|====

** Detailed Hardware Specs per Hypervisor:
----
DELL: <Model>
1 - <Model> Server with Dual 8C CPU, Dual QPI, 128GB
1 - PowerEdge R720, Intel速 Xeon速 E-26XX v2 Processors
1 - 2.5" Chassis with up to 16 Hard Drives
2 - Intel速 Xeon速 E5-2650 v2 2.60GHz, 20M Cache, 8.0GT/s QPI, Turbo, HT,
8C, 95W, Max Mem 1866MHz
1 - Performance Optimized
8 - 16GB RDIMM, 1866 MT/s, Standard Volt, Single Rank, x4 Data Width
1 - PERC H710P Integrated RAID Controller, 1GB NV Cache
2 - 300GB 10K RPM SAS 6Gbps 2.5in Hot-plug Hard Drive
1 - iDRAC7, Enterprise with OpenManage Essentials,Server ConfigMgmt
1 - Risers with up to 6, x8 PCIe Slots + 1, x16 PCIe Slot
1 - Intel Ethernet I350 QP 1Gb Network Daughter Card
1 - Intel Ethernet X540 Dual Port 10GBASE-T Server Adapter
1 - No Internal Optical Drive
1 - No Bezel
1 - Dual, Hot-plug, Redundant Power Supply (1+1), 750W
2 - Power Cord, C13 to C14, PDU Style, 12 Amps, 2 foot, Qty 1
1 - ReadyRails Sliding Rails Without Cable Management Arm
1 - 3 Year ProSupport and NBD On-site Service
1 - PowerEdge R720 Shipping
----


=== Networks

[width="100%",options="header"]
|====
| Name | VM? | On hosts | Special attributes | Notes
| 
| 
| 
| 
|====

=== OpenStack Templates

Template creation was explained and the customer was able to create
their own templates from VMs.

=== Create VM

For demonstration purposes, two VMs were created, one from the RHEL 6
DVD ISO and one from the RHEL 7 ISO.  The customer also was able to
create virtual machines including demonstrating their ability to
provision.

