== Document Information

=== Originator
Red Hat Consulting

{consultant1} <{consultant1_email}>

{consultant2} <{consultant2_email}>

=== Owner
Red Hat Consulting – Confidential. Restricted distribution.

=== Copyright
This document contains proprietary information which is for exclusive use of Red Hat, Inc. and is not to be shared with personnel other than Red Hat, Inc.  This document, and any portion thereof, may not be copied, reproduced, photocopied, stored electronically on a retrieval system, or transmitted without the express written consent of the owner.

Red Hat Professional Services does not warrant this document to be free of errors or omissions.  Red Hat Professional Services reserves the right to make corrections, updates, revisions, or changes to the information contained herein.  Red Hat Professional Services does not warrant the material described herein to be free of patent infringement.

Unless provided otherwise in writing by RED HAT Professional Services, the information and programs described herein are provided “as is” without warranty of any kind, including but not limited to the implied warranties of merchantability and fitness for a particular purpose. In no event will RED HAT Professional Services, its officers, directors, or employees or affiliates of RED HAT Professional Services, their respective officers, directors, or employees be liable to any entity for any special, collateral, incidental, or consequential damages, including without any limitation, for any lost profits or lost savings, related or arising in any way from or out of the use or inability to use the information or programs set forth herein, even if it has been notified of the possibility of such damage by the purchaser or any third party.

=== Distribution
Do not forward or copy without written permission.

Copies of this document are restricted to the following:

Red Hat, Inc.

{customer}

=== Confidentiality
All information supplied to {customer} for the purpose of this project is to be considered Red Hat confidential.

=== Additional copies
Further copies of this document can be obtained from:

{consultant1} <{consultant1_email}>

{consultant2} <{consultant2_email}>

